### ISSUE TITLE
notebook10a extract year

### ISSUE THREAD

**Issue by EricLaw-LYL** [statmlben/CUHK-STAT3009#1]
Instead of using
`year_tmp = re.findall('\d+', row['title'])`
It is better to use
`year_tmp = re.findall("\((\d{4})\)", row['title'])`

Because some moives might contain number in title, e.g. 17 Again (2009), using `"\d+"` will extract 17 as year

**Comment by statmlben** [comment]
Thanks @EricLaw-LYL . I have revised it in Notebook 9 as

year_tmp = re.findall('\((\d+)\)', row['title'])

Your solution also works! I will update it for NB10 soon.
